stages:
  - check
  - test

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/Rlibs"
  CRAN: "https://cran.r-project.org"

before_script:
  - mkdir Rlibs
  - Rscript -e "install.packages(c('devtools', 'rcmdcheck', 'foreach','ncdf4','raster','sf','zoo','lubridate','stars','ggplot2','tidyr','rdwd','dwdradar','R.utils','utils','terra','foreach','parallel','doParallel','gridExtra','httr','httr2','devtools','RColorBrewer','tidyverse','RSelenium','stringr','rvest','sp','geosphere','RCurl','grDevices','tidyselect','openeo','magrittr','jsonlite','dplyr','readxl','scales','methods','testthat'), repos=Sys.getenv('CRAN'))"

check:
  stage: check
  script:
    - Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning')"

test:
  stage: test
  script:
    - Rscript -e "devtools::test()"
